### PR TITLE
feat: Add support for filtering encrypted field by list of values

### PR DESCRIPTION
**Pull request by SteveKekacs**
Took a stab at implementing a fix for https://github.com/47ng/prisma-field-encryption/issues/119.

### CODE REVIEW

**Review by franky47 — CHANGES_REQUESTED** [review]
Thanks for this feature!

A couple of things could do with some changes (field naming and checking for arrays), otherwise it looks good.

**Comment by m-przybylski** [comment]
@SteveKekacs Can we please move forward with this PR? If you do not have time I could take over and apply changes from comments. I really need this feature in my project. Thanks.

**Comment by SteveKekacs** [comment]
> @SteveKekacs Can we please move forward with this PR? If you do not have time I could take over and apply changes from comments. I really need this feature in my project. Thanks.


Hi @m-przybylski, apologies, I'm no longer using this library so go ahead and take over.

**Comment by franky47** [comment]
Superseded by #136.

**Pull request closed without merging**
